@startuml

title __MOVIE's Class Diagram__\n

  package model {
    package model.primary {
      package model.primary.movie {
        enum Genre {
          ACTION
          ADVENTURE
          ANIMATION
          CHILDRENS
          COMEDY
          CRIME
          DOCUMENTARY
          DRAMA
          FANTASY
          FILM_NOIR
          HORROR
          MUSICAL
          MYSTERY
          ROMANCE
          SCI_FI
          THRILLER
          WAR
          WESTERN
        }
      }
    }
  }
  

  package model {
    package model.primary {
      package model.primary.movie {
        class Movie {
            - id : int
            - title : String
            - genreList : List<Genre>
            + Movie()
            - ID()
            - generateList()
            - genreStringList()
            - genre()
            - genreIndex()
            - genreIndexFound()
            + getId()
            + getTitle()
            + getGenreList()
        }
      }
    }
  }
  

  package model {
    package model.primary {
      package model.primary.movie {
        class MovieInfo {
            - idMovieMap : Map<Integer, Movie>
            + MovieInfo()
            + getTitle()
            + getGenreList()
            + printRatedMovies()
        }
      }
    }
  }
  

  package model {
    package model.primary {
      package model.primary.movie {
        class RatingAndTime {
            - rating : int
            - time : String
            + getRating()
            + getTime()
            + RatingAndTime()
            - returnRating()
            - validRating()
            + toString()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
